/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package simuladorcarro.views;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import simuladorcarro.models.Vehiculo;

/**
 * Diálogo que muestra la animación de patinaje del vehículo.
 * 
 * Muestra un GIF animado de pérdida de tracción y reproduce el sonido correspondiente
 * cuando el vehículo patina debido a un frenado brusco o exceso de velocidad
 * 
 * @author SOFIA RUDAS
 * @version 1.0.0
 * @since 12042025
 */
public class patinando extends javax.swing.JDialog {

    private Vehiculo vehiculo;
    
    /**
     * Crea un nuevo diálogo de patinaje.
     * 
     * @param parent Ventana padre del diálogo
     * @param modal Indica si el diálogo es modal
     * @param vehiculo Vehículo que está patinando
     * @param ventana Referencia a la ventana principal
     */
    public patinando(java.awt.Frame parent, boolean modal, Vehiculo vehiculo, principal ventana) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        reproducirSonido("/simuladorcarro/audios/patinando.wav");
        ImageIcon gif = new ImageIcon("/simuladorcarro/videos/patinar.gif");
        JLabel etiqueta = new JLabel(gif);
        etiqueta.setHorizontalAlignment(SwingConstants.CENTER);
        etiqueta.setVerticalAlignment(SwingConstants.CENTER);
        getContentPane().add(etiqueta);

        this.vehiculo = vehiculo;
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/simuladorcarro/images/logo.png")).getImage());
            
        }catch(Exception e){
            
        }
    }
    /**
     * Reproduce un sonido desde la ruta especificada.
     * 
     * @param ruta Ruta relativa del archivo de audio (formato WAV)
     */
    public void reproducirSonido(String ruta) {
        try {
            AudioInputStream audioInput = AudioSystem.getAudioInputStream(getClass().getResource(ruta));
            Clip clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start();
        } catch (Exception e) {
            System.out.println("Error al reproducir el sonido: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladorcarro/videos/patinar.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
